version: '3.3'

services:
  postgres:
    container_name: ${POSTGRES_HOST}
    image: postgres
    networks:
      - 3meg-network
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_DB=${POSTGRES_DB_NAME}

  redis:
    image: redis:alpine
    container_name: ${REDIS_HOST}
    volumes:
      - redis-data:/data
    networks:
      - 3meg-network

  monitoring:
    image: 3megawatt/dev-recruiting-challenge-monitor
    container_name: ${MONITORING_HOST}
    networks:
      - 3meg-network

  backend: &backend
    restart: always
    container_name: 3meg_backend
    build:
      context: ./src
      dockerfile: scripts/dev/Dockerfile
    command: /run_uwsgi.sh
    volumes:
      - django-static:/app/files/static
    ports:
      - "${APP_PORT}:8000"
    environment:
      - PROKECT_NAME=${PROKECT_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - CELERY_BROKER_HOST=${CELERY_BROKER_HOST}
      - CELERY_BROKER_TRANSPORT=${CELERY_BROKER_TRANSPORT}
      - CELERY_BROKER_PORT=${CELERY_BROKER_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - MONITORING_HOST=${MONITORING_HOST}
      - MONITORING_TRANSPORT=${MONITORING_TRANSPORT}
      - MONITORING_PORT=${MONITORING_PORT}
      - DATAPOINT_FETCH_URL_FORMAT=${DATAPOINT_FETCH_URL_FORMAT}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    networks:
      - 3meg-network
    depends_on:
      - redis
      - postgres
  celery:
    <<: *backend
    container_name: 3meg_celery
    build:
      context: ./src
      dockerfile: scripts/dev/Dockerfile
    command: bash -c 'celery -A config worker -l info'
    ports: []

  beat:
    <<: *backend
    container_name: 3meg_beat
    build:
      context: ./src
      dockerfile: scripts/dev/Dockerfile
    command: /run_beat.sh
    ports: []

volumes:
  pg-data:
  django-static:
  redis-data:

networks:
  3meg-network:
    driver: bridge
