version: '3.3'

services:

  redis:
    image: redis:alpine
    container_name: ${REDIS_HOST}
    volumes:
      - redis-data:/data
    networks:
      - 3meg-network

  backend: &backend
    restart: always
    container_name: 3meg_backend
    build:
      context: ./src
      dockerfile: scripts/dev/Dockerfile
    command: /run_uwsgi.sh
    volumes:
      - django-static:/app/files/static
    ports:
      - "8000:8000"
    environment:
      - PROKECT_NAME=${PROKECT_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - CELERY_BROKER_HOST=${CELERY_BROKER_HOST}
      - CELERY_BROKER_TRANSPORT=${CELERY_BROKER_TRANSPORT}
      - CELERY_BROKER_PORT=${CELERY_BROKER_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - 3meg-network
    depends_on:
      - redis

  celery:
    <<: *backend
    container_name: 3meg_celery
    build:
      context: ./src
      dockerfile: scripts/dev/Dockerfile
    command: bash -c 'celery -A config worker -l info'
    ports: []

  beat:
    <<: *backend
    container_name: 3meg_beat
    build:
      context: ./src
      dockerfile: scripts/dev/Dockerfile
    command: /run_beat.sh
    ports: []

volumes:
  django-static:
  redis-data:

networks:
  3meg-network:
    driver: bridge
