# Generated by Django 2.2.9 on 2020-02-11 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
            },
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_expected', models.DecimalField(decimal_places=14, max_digits=20, verbose_name='Expected Energy')),
                ('energy_observed', models.DecimalField(decimal_places=14, max_digits=20, verbose_name='Observed Energy')),
                ('irradiation_expected', models.DecimalField(decimal_places=14, max_digits=20, verbose_name='Expected Irradiation')),
                ('irradiation_observed', models.DecimalField(decimal_places=14, max_digits=20, verbose_name='Observed Irradiation')),
                ('datetime', models.DateTimeField(db_index=True, verbose_name='datetime')),
                ('date_created', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.Plant')),
            ],
            options={
                'verbose_name': 'Data Point',
                'verbose_name_plural': 'Data Points',
                'ordering': ['-date_created'],
            },
        ),
    ]
