# Generated by Django 2.2.10 on 2020-02-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='source_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Source Plant ID'),
            preserve_default=False,
        ),
    ]
